version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "photo-app-users-api-cognito-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s4bev8b7k3xe"
s3_prefix = "photo-app-users-api-cognito-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
confirm_changeset = true
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
